#!/bin/sh
#
# Check the QBE output of alic vs. alica
#

# Build our compiler if needed
if [ ! -f ../alica ]
then (cd ..; make)
fi

# Also ensure we have test files
make out err test001.al > /dev/null 2> /dev/null

# Try to use each input source file
for i in test*.al
do
  qfile=`echo $i | sed 's/al$/q/'`
  # Use the C version of the compiler
  # and get the checksum
  ../../alic -S $i 2> /dev/null
  csum=`cat $qfile | md5sum | sed 's/ .*//'`
  # Now use the compiler in alic
  ../alica -S $i 2> /dev/null
  asum=`cat $qfile | md5sum | sed 's/ .*//'`
  if [ "$asum" != "$csum" ]
  then echo $i: FAIL
  fi
done
rm *.q *.s
exit 0
